# Generated by Django 5.2.8 on 2026-01-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=200, verbose_name="Descricao")),
                ("category", models.CharField(choices=[("MAN", "Manutencao"), ("MIS", "Missoes"), ("SOC", "Social"), ("ADM", "Administrativo"), ("OUT", "Outros")], max_length=3, verbose_name="Categoria")),
                ("value", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Valor")),
                ("date", models.DateField(verbose_name="Data da saida")),
                ("payment_method", models.CharField(choices=[("DIN", "Dinheiro"), ("PIX", "PIX"), ("CAR", "Cartao de Debito/Credito")], max_length=3, verbose_name="Meio de pagamento")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Observacoes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Saida",
                "verbose_name_plural": "Saidas",
                "ordering": ["-date"],
            },
        ),
    ]
