# Generated by Django 5.0.6 on 2024-06-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('date_birth', models.DateField(verbose_name='data_aniversario')),
                ('date_baptism', models.DateField(verbose_name='data_batismo')),
                ('address', models.CharField(max_length=200, verbose_name='endereço')),
                ('cep', models.CharField(max_length=8, verbose_name='cep')),
            ],
        ),
    ]
