# Generated by Django 5.0.6 on 2024-06-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
