# Generated by Django 5.0.6 on 2024-06-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0002_member_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cpf',
            field=models.CharField(max_length=11, null=True, verbose_name='cpf'),
        ),
    ]
