# Generated by Django 5.0.6 on 2024-06-22 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0005_city_state_alter_member_date_birth_member_city_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='nationality',
        ),
        migrations.AddField(
            model_name='member',
            name='state_birth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estado_nascimento', to='cadmember.state'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_birth',
            field=models.DateField(default=' ', verbose_name='data_nascimento'),
        ),
    ]
