# Generated by Django 5.0.6 on 2024-06-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0007_rename_date_birth_member_data_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='cep',
            new_name='Cep',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='city_birth',
            new_name='Cidade de Nascimento',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='cpf',
            new_name='Cpf',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='date_baptism',
            new_name='Data de Batismo',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Data Nascimento',
            new_name='Data de Nascimento',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='address',
            new_name='Endereço',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='state_birth',
            new_name='Estado deNascimento',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='Nome',
        ),
    ]
