# Generated by Django 5.0.6 on 2024-06-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0008_rename_cep_member_cep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Endereço',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Cep',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Cidade de Nascimento',
            new_name='city_birth',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Cpf',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Data de Batismo',
            new_name='date_baptism',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Data de Nascimento',
            new_name='date_birth',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Estado deNascimento',
            new_name='state_birth',
        ),
    ]
