# Generated by Django 5.0.6 on 2024-07-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0009_rename_endereço_member_address_rename_cep_member_cep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='date_baptism',
            new_name='batismo_pessoa',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='cep',
            new_name='cep_pessoa',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='city_birth',
            new_name='cidade_pessoa',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='cpf',
            new_name='cpf_pessoa',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='address',
            new_name='endereco_pessoa',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='state_birth',
            new_name='estado_pessoa',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='date_birth',
            new_name='nascimento_pessoa',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='nome_pessoa',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='estado',
        ),
    ]
