# Generated by Django 5.0.6 on 2024-07-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0011_rename_endereco_pessoa_member_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='cidade',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='estado',
            new_name='state',
        ),
    ]
