# Generated by Django 5.0.6 on 2024-07-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0012_rename_cidade_city_city_rename_estado_state_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='estado',
        ),
    ]
