# Generated by Django 5.0.6 on 2024-07-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0013_rename_city_city_cidade_rename_state_state_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='cidade',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='estado',
            new_name='state',
        ),
    ]
