# Generated by Django 5.1.7 on 2025-03-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0015_alter_member_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dizimista',
            field=models.BooleanField(default=False, verbose_name='dizimista'),
        ),
        migrations.AddField(
            model_name='member',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='telefone'),
        ),
    ]
