# Generated by Django 5.1.7 on 2025-03-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0016_member_dizimista_member_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Membro', 'verbose_name_plural': 'Membros'},
        ),
    ]
