# Generated by Django 5.1.7 on 2025-03-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0018_member_created_at_member_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
