# Generated by Django 5.1 on 2026-01-10 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0023_import_all_cities_with_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data da contribuição')),
                ('type', models.CharField(choices=[('DIZ', 'Dízimo'), ('OFE', 'Oferta Geral'), ('ESP', 'Oferta Especial')], max_length=3, verbose_name='Tipo de contribuição')),
                ('payment_method', models.CharField(choices=[('DIN', 'Dinheiro'), ('PIX', 'PIX'), ('CAR', 'Cartão de Débito/Crédito')], max_length=3, verbose_name='Meio de pagamento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='cadmember.member', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Contribuição',
                'verbose_name_plural': 'Contribuições',
                'ordering': ['-date'],
            },
        ),
    ]
