# Generated by Django 5.1 on 2026-01-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0024_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cidade_residencia', to='cadmember.city', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estado_residencia', to='cadmember.state', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='member',
            name='city_birth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cidade_nascimento', to='cadmember.city', verbose_name='Cidade de Nascimento'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_birth',
            field=models.DateField(default=' ', verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='member',
            name='state_birth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estado_nascimento', to='cadmember.state', verbose_name='Estado de Nascimento'),
        ),
    ]
