# Generated by Django 5.1 on 2026-01-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmember', '0026_alter_member_city_alter_member_city_birth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
