# Generated by Django 5.2.8 on 2026-01-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadmember", "0027_delete_contribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="address_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Numero"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="birth_address",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Endereco de Nascimento",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="birth_address_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Numero Nascimento"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="birth_bairro",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Bairro de Nascimento",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="birth_cep",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="CEP de Nascimento"
            ),
        ),
    ]
